# Generated by Django 3.1.3 on 2020-11-28 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unidade', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidade', to='unidade.unidade', verbose_name='Unidade de Pronto Atendimento *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo'),
        ),
    ]
