# Generated by Django 3.1.3 on 2020-11-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triagem', '0002_auto_20201128_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triagem',
            name='hora',
            field=models.TimeField(blank=True, help_text='hh:mm', max_length=5, verbose_name='Hora do atendimento *'),
        ),
        migrations.AlterField(
            model_name='triagem',
            name='idade',
            field=models.PositiveIntegerField(verbose_name='Idade'),
        ),
    ]
